trigger:
- master

resources:
- repo: self

variables:
  # subscription: ''
  # acrName: ''
  # resourceGroup: ''
  # deployfrom: 'Deploy'
  vmImage: 'ubuntu-18.04'
  imageName: 'bus-stop-docker'

stages:
- stage: Build
  jobs:
  - job: Deploy_Scripts
    pool:
      vmImage: '$(vmImage)'
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(Docker-RegCon)
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: Deploy/Dockerfile
- stage: Deploy
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy job
    pool:
      vmImage: '$(vmImage)'
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        appName: 'bus-stop'
        azureSubscription: $(subscription)
        imageName:  $(arcName)'.azurecr.io'/$(imageName):$(build.buildId)
